# Generated by Django 5.1.5 on 2025-01-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_level', models.IntegerField(default=1)),
                ('card_count', models.IntegerField(default=4)),
                ('numbers_sequence', models.JSONField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
