# Generated by Django 5.1.5 on 2025-01-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='numbers_sequence',
            field=models.JSONField(default=list),
        ),
    ]
