# Generated by Django 5.1.5 on 2025-01-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_colorpairsgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionalMemoryGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Directional Memory', max_length=100)),
                ('description', models.TextField(default='Memorize and replicate the arrow sequence')),
                ('icon', models.CharField(default='↔️', max_length=50)),
                ('url_path', models.CharField(default='directional-memory', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_level', models.IntegerField(default=1)),
                ('sequence_length', models.IntegerField(default=3)),
                ('arrow_sequence', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
